AWSTemplateFormatVersion: 2010-09-09
Description: The Monster of the Week site infrastructure

Parameters:
  DomainName:
    Type: String
    Default: monsterplaybook.rip

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  DnsName:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: s3-website-us-east-1.amazonaws.com
        HostedZoneId: Z3AQBSTGFYJSTF
        EvaluateTargetHealth: true
      HostedZoneId: !GetAtt HostedZone.Id
      Name: !Ref DomainName
      Type: A