AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Loads base data into the database

Parameters:
  TableName:
    Type: String
    Description: The name of the table to load data into
  Prefix:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  DataSns:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ["${Prefix}Data-Sns", { Prefix: !Ref Prefix}]

  DataSnsPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref DataSns
      Topics:
        - !Ref DataSns

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ["${Prefix}auspex-data", { Prefix: !Ref Prefix}]
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref DataSns
            Event: 's3:ObjectCreated:*'

  Armies:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: armies/template.yaml
      Parameters:
        TableName: !Ref TableName
        Prefix: !Ref Prefix
        DataSns: !Ref DataSns

Outputs:
  ArmiesLoadDataFunctionName:
    Value: !GetAtt Armies.Outputs.ArmiesLoadDataFunctionName
    Description: The name of the armies load data lambda function

  DataBucketName:
    Value: !Ref DataBucket
    Description: The name of the bucket to upload data to