phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "installing base packages"
      - npm i

      - echo "installing packages"
      - npm run install-all

      - echo "installing rust dependencies"
      - curl https://sh.rustup.rs -sSf | bash -s -- -y
      - source $HOME/.cargo/env
      - pip3 install cargo-lambda
  build:
    commands:
      - echo "building authorizer"
      - npm run build

      - echo "packaging authorizer packages"
      - npm run package