AWSTemplateFormatVersion: 2010-09-09
Description: The Monster of the Week site infrastructure

# Parameters:
#   DomainName:
#     Type: String
#     Default: monsterplaybook.rip

# Mappings:
#   Region2S3WebsiteSuffix:
#     us-east-1:
#       Suffix: .s3-website-us-east-1.amazonaws.com
#     us-west-1:
#       Suffix: .s3-website-us-west-1.amazonaws.com
#     us-west-2:
#       Suffix: .s3-website-us-west-2.amazonaws.com
#     eu-west-1:
#       Suffix: .s3-website-eu-west-1.amazonaws.com
#     ap-northeast-1:
#       Suffix: .s3-website-ap-northeast-1.amazonaws.com
#     ap-northeast-2:
#       Suffix: .s3-website-ap-northeast-2.amazonaws.com
#     ap-southeast-1:
#       Suffix: .s3-website-ap-southeast-1.amazonaws.com
#     ap-southeast-2:
#       Suffix: .s3-website-ap-southeast-2.amazonaws.com
#     ap-south-1:
#       Suffix: .s3-website-ap-south-1.amazonaws.com
#     us-east-2:
#       Suffix: .s3-website-us-east-2.amazonaws.com
#     sa-east-1:
#       Suffix: .s3-website-sa-east-1.amazonaws.com
#     cn-north-1:
#       Suffix: .s3-website.cn-north-1.amazonaws.com.cn
#     eu-central-1:
#       Suffix: .s3-website.eu-central-1.amazonaws.com

Resources:
  # CloudFrontOriginIdentity:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Properties:
  #     CloudFrontOriginAccessIdentityConfig:
  #       Comment: !Ref UiBucket

  # CertificateManagerCertificate:
  #   Type: AWS::CertificateManager::Certificate
  #   Properties:
  #     DomainName: monsterplaybook.rip
  #     ValidationMethod: DNS
  #     DomainValidationOptions:
  #       - DomainName: www.monsterplaybook.rip
  #         HostedZoneId: !GetAtt HostedZone.Id

  # CloudFront:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       Aliases:
  #       # - !Join ['', [!Ref AWS::StackName, !Ref AWS::AccountId, ., !Ref AWS::Region, ., !Ref DomainName]]
  #       - !Ref DomainName
  #       Origins:
  #         - CustomOriginConfig:
  #             HTTPPort: 80
  #             HTTPSPort: 443
  #             OriginProtocolPolicy: http-only
  #           DomainName: !GetAtt UiBucket.DomainName
  #           Id: s3UiOrigin
  #       # Origins:
  #       # - DomainName: !GetAtt UiBucket.DomainName
  #       #   Id: s3UiOrigin
  #       #   S3OriginConfig:
  #       #     OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginIdentity}'
  #       Enabled: true
  #       DefaultRootObject: index.html
  #       # HttpVersion: http2
  #       DefaultCacheBehavior:
  #         # AllowedMethods:
  #         #   - GET
  #         #   - HEAD
  #         #   - OPTIONS
  #         # CachedMethods:
  #         #   - GET
  #         #   - HEAD
  #         #   - OPTIONS
  #         # Compress: true
  #         # DefaultTTL: 3600 # in seconds
  #         # MaxTTL: 86400
  #         # MinTTL: 60
  #         TargetOriginId: s3UiOrigin
  #         ViewerProtocolPolicy: allow-all
  #         ForwardedValues:
  #           QueryString: true
  #       ViewerCertificate:
  #         AcmCertificateArn: !Ref CertificateManagerCertificate
  #         MinimumProtocolVersion: TLSv1.1_2016
  #         SslSupportMethod: sni-only

  # DnsName:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     AliasTarget:
  #       DNSName: !GetAtt UiBucket.DomainName
  #       HostedZoneId: !GetAtt HostedZone.Id
  #       EvaluateTargetHealth: true
  #     HostedZoneId: !GetAtt HostedZone.Id
  #     Name: !Ref DomainName
  #     Type: A
  #     # ResourceRecords:
  #     # - !GetAtt CloudFront.DomainName

  # RecordSetGroup:
  #   Type: AWS::Route53::RecordSetGroup
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     RecordSets:
  #     - Name: !Ref DomainName
  #       Type: A
  #       AliasTarget:
  #         DNSName: !GetAtt CloudFront.DomainName
  #         EvaluateTargetHealth: false
  #         HostedZoneId: !Ref HostedZone
  #     - Name: !Sub 'www.${DomainName}'
  #       Type: A
  #       AliasTarget:
  #         DNSName: !GetAtt CloudFront.DomainName
  #         EvaluateTargetHealth: false
  #         HostedZoneId: !Ref HostedZone

  # HostedZone:
  #   Type: AWS::Route53::HostedZone
  #   Properties:
  #     Name: !Ref DomainName

  # Route53Record:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     Name:
  #     HostedZoneId: !GetAtt HostedZone.Id
  #     AliasTarget:
  #       DNSName: !GetAtt CloudFront.DomainName
  #       HostedZoneId: !Ref HostedZone

  UiBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UiBucket
      PolicyDocument:
        Id: UiBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: ReadAccess
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub '${UiBucket.Arn}/*'

  UiBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub ${AWS::StackName}
      # PublicAccessBlockConfiguration:
      #   BlockPublicAcls: True
      #   BlockPublicPolicy: True
      #   IgnorePublicAcls: True
      #   RestrictPublicBuckets: True
      WebsiteConfiguration:
        IndexDocument: index.html
        # ErrorDocument: error.html

Outputs:
  UiBucketName:
    Value: !Ref UiBucket
    Description: The name of the UI bucket
    Export:
      Name: UiBucketName
  WebsiteURL:
    Value: !GetAtt UiBucket.WebsiteURL
    Description: URL for website hosted on S3
  UiBucketDomainName:
    Value: !GetAtt UiBucket.DomainName
    Description: The domain name of the UI bucket.
    Export:
      Name: UiBucketDomainName
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt UiBucket.DomainName
    Description: Name of S3 bucket to hold website content