AWSTemplateFormatVersion: 2010-09-09
Description: The Monster of the Week site infrastructure

Resources:
  UiBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub ${AWS::StackName}
      VersioningConfiguration:
        Status: Enabled