AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Loads base data into the database

Parameters:
  TableName:
    Type: String
    Description: The name of the table to load data into

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  LoadDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: rust-cargolambda # More info about Cargo Lambda: https://github.com/cargo-lambda/cargo-lambda
    Properties:
      FunctionName: LoadDataFunction
      CodeUri: rust_app/target/lambda/load-data
      Handler: bootstrap    # Do not change, as this is the default executable name produced by Cargo Lambda
      Runtime: provided.al2
      Architectures:
        - x86_64
      Environment:
        Variables:
          Table: !Ref TableName

Outputs:
  LoadDataFunctionName:
    Value: !Ref LoadDataFunction
    Description: The name of the load data lambda function
    Export:
      Name: LoadDataFunctionName