AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Monster of the Week api gateway infrastructure

Resources:
  ApiGateway: 
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: The Monster of the Week API
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Sub ${AWS::StackName}-ApiGateway

  Authorizer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../../api/authorizer/template.yaml
      Parameters:
        ApiGatewayId: !Ref ApiGateway

  V1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../../api/v1/template.yaml
      Parameters:
        ApiGatewayId: !Ref ApiGateway
        RootResourceId: !GetAtt ApiGateway.RootResourceId
        AuthorizerId: !GetAtt Authorizer.Outputs.ApiAuthorizerId
    DependsOn: Authorizer

  # V2:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ../../../api/v2/template.yaml
  #     Parameters:
  #       ApiGatewayId: !Ref ApiGateway
  #       RootResourceId: !GetAtt ApiGateway.RootResourceId
  #       AuthorizerId: !GetAtt Authorizer.Outputs.ApiAuthorizerId
  #   DependsOn: Authorizer

Outputs:
  ApiGatewayId:
    Value: !Ref ApiGateway
    Description: The ID of the api gateway
    Export:
      Name: ApiGatewayId

  RootResourceId:
    Value: !GetAtt ApiGateway.RootResourceId
    Description: The ID of the api root resource
    Export:
      Name: RootResourceId