AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Monster of the Week api gateway infrastructure

Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: The Monster of the Week API
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Sub ${AWS::StackName}-ApiGateway

  MockGet:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../../api/test/get/template.yaml
      Parameters:
        ApiGatewayId: !Ref ApiGateway