AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Monster of the Week api gateway infrastructure

Resources:
  ApiGateway: 
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: The Monster of the Week API
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Sub ${AWS::StackName}-ApiGateway

  AuthorizerFunction:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      RestApiId: !Ref ApiGateway
      Name: GoogleAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      AuthorizerResultTtlInSeconds: 300
      ProviderARNs:
        - arn:aws:cognito-idp:us-east-1:625961017727:userpool/us-east-1_Ivg0PFznF
      # AuthorizerCredentials: '{{resolve:secretsmanager:GoogleCredentials:SecretString:client_id}}'

  V1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../../api/v1/template.yaml
      Parameters:
        ApiGatewayId: !Ref ApiGateway
        RootResourceId: !GetAtt ApiGateway.RootResourceId

  V2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../../api/v2/template.yaml
      Parameters:
        ApiGatewayId: !Ref ApiGateway
        RootResourceId: !GetAtt ApiGateway.RootResourceId

Outputs:
  ApiGatewayId:
    Value: !Ref ApiGateway
    Description: The ID of the api gateway
    Export:
      Name: ApiGatewayId

  RootResourceId:
    Value: !GetAtt ApiGateway.RootResourceId
    Description: The ID of the api root resource
    Export:
      Name: RootResourceId