AWSTemplateFormatVersion: 2010-09-09
Description: The 40k Auspex Database

Resources:
  40kAuspexTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 40kAuspexTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: type
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: type-index
          KeySchema:
            - AttributeName: type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  DbTableName:
    Value: !Ref 40kAuspexTable
    Description: The table name for 40k Auspex
    Export:
      Name: DbTableName