AWSTemplateFormatVersion: 2010-09-09
Description: The 40k Auspex Database

Resources:
  40kAuspexTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 40kAuspexTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        # - AttributeName: data
        #   AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: type
          KeyType: RANGE
        # - AttributeName: data
        #   KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  LambdaLoad:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../load-data/template.yaml
      Parameters:
        TableName: !Ref 40kAuspexTable

Outputs:
  DbTableName:
    Value: !Ref 40kAuspexTable
    Description: The table name for 40k Auspex
    Export:
      Name: DbTableName

  LoadDataName:
    Value: !GetAtt LambdaLoad.Outputs.LoadDataFunctionName
    Description: The name of the load data lambda function
    Export:
      Name: LoadDataName