AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: The lambda to delete the stack

Resources:
  DeleteStacksLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DeleteStacksLambdaRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs
      Policies:
      - PolicyName: delete-stacks-lambda-policy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
              - iam:*
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/40k-auspex-roles-*"
          - Effect: Allow
            Action:
              - codebuild:DeleteProject
            Resource: !Sub "arn:aws:codebuild:us-east-1:${AWS::AccountId}:project/*"
          - Effect: Allow
            Action:
              - codepipeline:*
            Resource: "*"
  
  DeleteStacksLambda:
   Type: AWS::Serverless::Function
   Properties:
    FunctionName: DeleteStacks
    Description: A lambda used to delete stacks for lower environments
    Handler: index.handler
    Role: !GetAtt DeleteStacksLambdaRole.Arn
    Runtime: nodejs18.x
    CodeUri: dist
    AutoPublishAlias: live
    Timeout: 900

Outputs:
  DeleteStacksLambdaArn:
    Value: !GetAtt DeleteStacksLambda.Arn
    Description: The arn of the delete stacks lambda