AWSTemplateFormatVersion: 2010-09-09
Description: The authentication endpoints

Resources:
  GetDataSheet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: buld/getDataSheet
      Handler: index.handler
      Runtime: nodejs16.x
      Events:
        Api:
          Type: Api
          Properties:
            Path: /data-sheet
            Method: get

  PostDataSheet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/postDataSheet
      Handler: index.handler
      Runtime: nodejs16.x
      Events:
        Api:
          Type: Api
          Properties:
            Path: /data-sheet
            Method: post
