AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Monster of the Week site infrastructure

Parameters:
  DomainName:
    Type: String
    Default: monsterplaybook.rip
  HostedZoneId:
    Type: String
    Default: Z0953270AK2JGXA33JIB
  CloudFronCert:
    Type: String
    Default: arn:aws:acm:us-east-1:625961017727:certificate/edd15537-9b78-4e21-a100-9ce277ca42bf
  Domain:
    Type: String
    AllowedPattern: (.*[.])*monsterplaybook.rip

Mappings:
  AliasMap:
    staging:
      Alias: staging.monsterplaybook.rip
    production:
      Alias: monsterplaybook.rip

Resources:
  LambdaEdgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowLambdaServiceToAssumeRole
            Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
      Path: /
      Policies:
        - PolicyName: EdgeLambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: '*'
              - Action:
                  - lambda:EnableReplication*
                Effect: Allow
                Resource: '*'
              - Action:
                  - s3:*
                Effect: Allow
                Resource: "*"

  LambdaEdge:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Role: !GetAtt LambdaEdgeRole.Arn
      Runtime: nodejs16.x
      Handler: index.handler
      Timeout: 5
      AutoPublishAlias: live

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Domain
        Origins:
          - DomainName: aws.amazon.com
            Id: lambdaEdgeId
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: match-viewer
        Enabled: true
        Comment: The monster of the week cloud front distribution
        DefaultCacheBehavior:
          TargetOriginId: lambdaEdgeId
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref LambdaEdge.Version
          ForwardedValues:
            QueryString: false
            Headers:
                - Origin
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFronCert
          SslSupportMethod: sni-only

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref LambdaEdge]]
  
  DnsName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
      - Name: !Ref Domain
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt CloudFrontDistribution.DomainName