AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Monster of the Week site infrastructure

Parameters:
  DomainName:
    Type: String
    Default: monsterplaybook.rip
  HostedZoneId:
    Type: String
    Default: Z0953270AK2JGXA33JIB
  CloudFronCert:
    Type: String
    Default: arn:aws:acm:us-east-1:625961017727:certificate/edd15537-9b78-4e21-a100-9ce277ca42bf
  Domain:
    Type: String
    AllowedPattern: (.*[.])*monsterplaybook.rip
  BranchName:
    Type: String

Mappings:
  AliasMap:
    staging:
      Alias: staging.monsterplaybook.rip
    production:
      Alias: monsterplaybook.rip

Resources:
  ##################### CloudFront
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI from ${Domain}'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Origins:
          - DomainName: !Sub
            - '${BranchName}/${UiBucketDomainName}'
            - BranchName: !Ref BranchName
              UiBucketDomainName: !ImportValue UiBucketDomainName
            Id: ui-bucket
            S3OriginConfig:
              OriginAccessIdentity: !Join ["", ["origin-access-identity/cloudfront/", !Ref CloudFrontOAI]]
        DefaultRootObject: !Sub '${BranchName}/index.html'
        Enabled: true
        IPV6Enabled: true
        DefaultCacheBehavior:
          Compress: true
          TargetOriginId: ui-bucket
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
        HttpVersion: http2
        Comment: The monster of the week cloud front distribution
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFronCert
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only

  ##################### DNS
  DnsName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
      - Name: !Ref Domain
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt CloudFrontDistribution.DomainName

  ##################### Bucket
  UiBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !ImportValue UiBucketName
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub
              - "${BucketArn}/*"
              - BucketArn: !ImportValue UiBucketArn
            Principal:
              Service: cloudfront.amazonaws.com
              AwS: !Sub
                - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OAI}'
                - OAI: !Ref CloudFrontOAI