version: 0.2

env:
  shell: bash
batch: 
  build-list:
    - identifier: authorizer
      env:
        variables:
          LOCATION: authorizer
      ignore-failure: false
    - identifier: v1
      env:
        variables:
          LOCATION: v1
      ignore-failure: false
    - identifier: v2
      env:
        variables:
          LOCATION: v2
      ignore-failure: false
  # build-matrix:
  #   static:
  #     env:
  #       type: LINUX_CONTAINER
  #   dynamic:
  #     env:
  #       variables:
  #         LOCATION:
  #           - authorizer
  #           - v1
  #           - v2
  
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - printenv
      - echo $LOCATION
      - echo "installing base packages"
      - npm i

      - echo "navigating to api"
      - cd api

      - echo "installing rust dependencies"
      - curl https://sh.rustup.rs -sSf | bash -s -- -y
      - source $HOME/.cargo/env
      - pip3 install cargo-lambda
  build:
    commands:
      - pwd
      - echo "navigating to ${LOCATION}"
      - cd ${LOCATION}
      - pwd

      - echo "building ${LOCATION}"
      - npm run build

      - echo "packaging ${LOCATION} packages"
      - npm run package