version: 0.2

batch: 
  build-graph:
    - identifier: authorizer
      buildspec: infrastructure/pipeline/endpoints-build.yaml
      env:
        variables:
          LOCATION: authorizer
      ignore-failure: false
    - identifier: v1
      buildspec: infrastructure/pipeline/endpoints-build.yaml
      env:
        variables:
          LOCATION: v1
      ignore-failure: false
    - identifier: v2
      buildspec: infrastructure/pipeline/endpoints-build.yaml
      env:
        variables:
          LOCATION: v2
      ignore-failure: false