version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "installing base packages"
      - npm i
      - echo "installing packages"
      - npm run install-all
  build:
    commands:
      - echo "building packages"
      - npm run build-all
      - echo "packaging packages"
      - npm run package-all
  post_build:
    commands:
      - cd url
      - ls -a

artifacts:
  files:
    - '*'
  secondary-artifacts:
    uiBuildOutput:
      base-directory: ui/build
      files:
        - '**/*'
    lambdaEdgeBuildOutput:
      base-directory: infrastructure/url
      files:
        - '**/*'