version: 0.2

env:
  shell: bash

batch:
  fast-fail: false
  build-graph:
    - identifer: api
      buildspec: api/buildspec-build.yaml
      debug-session: true
    - identifer: all
      buildspec: ./buildspec-build.yaml
      depend-on:
        - api