version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "installing base packages"
      - npm i
      - echo "installing packages"
      - npm run install-all
  build:
    commands:
      - echo "building packages"
      - npm run build-all
      - aws cloudformation package --template-file ../url/template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file ui.yaml
  post_build:
    commands:
      - cd ui/build/_app
      - ls -a

artifacts:
  base-directory: ui/build
  files:
    - '**/*'
    - ui.yaml