version: 0.2

env:
  shell: bash

batch:
  fast-fail: true
  build-graph:
    - identifer: authorizer
      base-directory: api/authorizer
      buildspec: buildspec-build.yaml
    - identifer: v1
      base-directory: api/v1
      buildspec: buildspec-build.yaml
    - identifer: v2
      base-directory: api/v2
      buildspec: buildspec-build.yaml
    - identifer: all
      base-directory: infrastructure
      buildspec: buildspec-build.yaml