version: 0.2

env:
  shell: bash

batch:
  fast-fail: true
  build-graph:
    debug-session: true
    - identifer: api
      buildspec: .api/api-build.yaml
      ignore-failure: false
    - identifer: all
      buildspec: .infrastructure/project-build.yaml
      ignore-failure: false
      depend-on:
        - api