version: 0.2

env:
  shell: bash

batch:
  fast-fail: false
  build-graph:
    - identifer: api
      base-directory: api
      buildspec: buildspec-build.yaml
    - identifer: all
      base-directory: infrastructure
      buildspec: buildspec-build.yaml