version: 0.2

env:
  shell: bash

batch:
  fast-fail: true
  build-graph:
    - identifer: api
      buildspec: api-build.yaml
      ignore-failure: false
      debug-session: true
    - identifer: all
      buildspec: project-build.yaml
      ignore-failure: false
      debug-session: true
      depend-on:
        - api