version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "installing base packages"
      - npm i
      - echo "installing packages"
      - npm run install-all
      - echo "installing rust dependencies"
      - curl https://sh.rustup.rs -sSf | bash -s -- -y
  build:
    commands:
      - echo "building packages"
      - npm run build-all
      - echo "packaging packages"
      - npm run package-all

artifacts:
  files:
    - '*'
  secondary-artifacts:
    uiBuildOutput:
      base-directory: ui/build
      files:
        - '**/*'
    lambdaEdgeBuildOutput:
      base-directory: infrastructure/url
      files:
        - '**/*'
    apiGatewayBuildOutput:
      base-directory: infrastructure/apiGateway
      files:
        - '**/*'
    apiGatewayDeploymentBuildOutput:
      base-directory: infrastructure/apiGatewayDeployment
      files:
        - '**/*'
    