version: 0.2

env:
  shell: bash

batch:
  fast-fail: false
  build-graph:
    - identifier: api
      buildspec: infrastructure/pipeline/api-build.yaml
      ignore-failure: false
      debug-session: true
    - identifier: all
      buildspec: infrastructure/pipeline/project-build.yaml
      ignore-failure: false
      debug-session: true
      depend-on:
        - api