version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "installing base packages"
      - npm i
      - echo "installing packages"
      - npm run install-all
  build:
    commands:
      - echo "building packages"
      - npm run build-all
      - cd infrastructure/url/
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file ui.yaml
  post_build:
    commands:
      - ls -a

artifacts:
  files:
    - '*'
  secondary-artifacts:
    uiBuildOutput:
      base-directory: ui/build
      files:
        - '**/*'
    lambdaEdgeBuildOutput:
      base-directory: infrastructure/url
      files:
        - ui.yaml