version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "installing base packages"
      - npm i
      - echo "installing packages"
      - npm run install-all
  build:
    commands:
      - echo "building packages"
      - npm run build-all
  post_build:
    commands:
      - cd ui/build
      - ls -a

artifacts:
  base-directory: ui/build
  files:
    - '*/**'