version: 0.2

env:
  shell: bash

batch:
  fast-fail: true
  build-graph:
    - identifer: api
      buildspec: ../../api/buildspec-build.yaml
    - identifer: all
      buildspec: ../buildspec-build.yaml
      depend-on:
        - api