version: 0.2

env:
  shell: bash
  
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "installing base packages"
      - npm i

      - echo "navigating to api"
      - cd api

      - echo "installing rust dependencies"
      - curl https://sh.rustup.rs -sSf | bash -s -- -y
      - source $HOME/.cargo/env
      - pip3 install cargo-lambda
  build:
    commands:
      - echo "navigating to $LOCATION"
      - cd ./$LOCATION

      - echo "building $LOCATION"
      - npm run build

      - echo "packaging $LOCATION packages"
      - npm run package

artifacts:
  files:
    - '*'
  secondary-artifacts:
    api:
      base-directory: api/$LOCATION/target/lambda
      files:
        - '**/*'