AWSTemplateFormatVersion: 2010-09-09
Description: The Monster of the Week Pipeline

Parameters:
  GitHubRepo:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: monster-of-week
  GitHubBranch:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: master

Conditions:
  IsProduction: !Equals [!Ref GitHubBranch, "master"]

Resources:
  BuildRunner:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-BuildRunner
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value: !ImportValue ArtifactBucketId
          - Name: S3_BUCKET
            Value: !ImportValue ArtifactBucketId
      ServiceRole: !ImportValue BuildExecutionRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/pipeline/buildspec-build.yaml

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${AWS::StackName}
      ArtifactStore:
        Type: S3
        Location: !ImportValue ArtifactBucketId
      RestartExecutionOnUpdate: true
      RoleArn: !ImportValue PipelineInfrastructureRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              InputArtifacts: []
              OutputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: "{{resolve:secretsmanager:Github:SecretString:owner}}"
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                PollForSourceChanges: false
                OAuthToken: "{{resolve:secretsmanager:Github:SecretString:token}}"
              RunOrder: 1
        - Name: Build
          Actions:
          - Name: Build
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref BuildRunner
            InputArtifacts:
              - Name: SourceCode
            OutputArtifacts:
              - Name: uiBuildOutput
              - Name: apiGatewayBuildOutput
              - Name: databaseBuildOutput
              - Name: apiGatewayDeploymentBuildOutput
            RunOrder: 1
        - Name: !If [IsProduction, 'Staging', !Ref GitHubBranch]
          Actions:
            - Name: DeployApi
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: apiGatewayBuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: apiGatewayBuildOutput::infrastructure/template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                StackName: !Sub '${AWS::StackName}-Stack-API'
              RunOrder: 1
            - Name: DeployUiCode
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: 1
              RunOrder: 2
              Configuration:
                BucketName: !ImportValue UiBucketName
                Extract: true
                ObjectKey: !If [IsProduction, 'master', !Ref GitHubBranch]
              InputArtifacts:
                - Name: uiBuildOutput
              Region: us-east-1
            - Name: DeployDatabase
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: databaseBuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: databaseBuildOutput::infrastructure/template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                StackName: !Sub '${AWS::StackName}-Stack-Database'
              RunOrder: 2
            - Name: SeedDatabase
              Actions:
                - Name: LoadData
                  ActionTypeId:
                    Category: Invoke
                    Owner: AWS
                    Version: 1
                    Provider: Lambda
                  Configuration:
                    FunctionName: !ImportValue LoadDataFunctionName
                  RunOrder: 3
            - Name: DeployApiStage
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: apiGatewayDeploymentBuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: apiGatewayDeploymentBuildOutput::infrastructure/template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                StackName: !Sub '${AWS::StackName}-Stack-Api-Deployment'
                ParameterOverrides: !Sub
                  - '{ "BasePathDomain": "${BasePathDomain}" }'
                  - BasePathDomain: !If [IsProduction, 'api.monsterplaybook.rip', !Sub 'api-${GitHubBranch}.monsterplaybook.rip']
              RunOrder: 2
        - !If
          - IsProduction
          - Name: DeploymentApproval
            Actions:
              - Name: Approval
                ActionTypeId:
                  Category: Approval
                  Owner: AWS
                  Provider: Manual
                  Version: 1
                RunOrder: 1
          - !Ref AWS::NoValue
        - !If
          - IsProduction
          - Name: Production
            Actions:
              - Name: DeployUiCode
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: S3
                  Version: 1
                RunOrder: 1
                Configuration:
                  BucketName: !ImportValue UiBucketName
                  Extract: true
                  ObjectKey: master
                InputArtifacts:
                  - Name: uiBuildOutput
                Region: us-east-1
              - Name: CreateUIChangeSet
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                Configuration:
                  ActionMode: CHANGE_SET_REPLACE
                  RoleArn: !ImportValue CloudFormationExecutionRoleArn
                  StackName: 'prod-Stack-UI'
                  ChangeSetName: ui
                  TemplatePath: lambdaEdgeBuildOutput::infrastructure/template.package.yaml
                  Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                  ParameterOverrides: '{ "Domain": "monsterplaybook.rip", "BranchName": "master" }'
                InputArtifacts:
                  - Name: lambdaEdgeBuildOutput
                RunOrder: 1
              - Name: CreateApiChangeSet
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                InputArtifacts:
                  - Name: apiGatewayBuildOutput
                Configuration:
                  ActionMode: CHANGE_SET_REPLACE
                  RoleArn: !ImportValue CloudFormationExecutionRoleArn
                  StackName: 'prod-Stack-Api'
                  ChangeSetName: api
                  TemplatePath: apiGatewayBuildOutput::infrastructure/template.package.yaml
                  Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                  ParameterOverrides: '{ "BasePathDomain": "api.monsterplaybook.rip" }'
                RunOrder: 1
              - Name: CreateApiDeploymentChangeSet
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                InputArtifacts:
                  - Name: apiGatewayDeploymentBuildOutput
                Configuration:
                  ActionMode: CHANGE_SET_REPLACE
                  RoleArn: !ImportValue CloudFormationExecutionRoleArn
                  StackName: !Sub 'prod-Stack-Api-Deployment'
                  ChangeSetName: api-deployment
                  TemplatePath: apiGatewayDeploymentBuildOutput::infrastructure/template.package.yaml
                  Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                RunOrder: 1
              - Name: ExecuteApiChangeSet
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                Configuration:
                  ActionMode: CHANGE_SET_EXECUTE
                  RoleArn: !ImportValue CloudFormationExecutionRoleArn
                  StackName: !Sub 'prod-Stack-Api'
                  ChangeSetName: api
                OutputArtifacts:
                  - Name: !Sub 'prod-ChangeSet-Api-Deploy'
                RunOrder: 2
              - Name: ExecuteUIChangeSet
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                Configuration:
                  ActionMode: CHANGE_SET_EXECUTE
                  RoleArn: !ImportValue CloudFormationExecutionRoleArn
                  StackName: !Sub '$prod-Stack-UI'
                  ChangeSetName: ui
                OutputArtifacts:
                  - Name: !Sub 'prod-ChangeSet-UI-Deploy'
                RunOrder: 3
              - Name: ExecuteApiDeploymentChangeSet
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                Configuration:
                  ActionMode: CHANGE_SET_EXECUTE
                  RoleArn: !ImportValue CloudFormationExecutionRoleArn
                  StackName: !Sub 'prod-Stack-Api-Deployment'
                  ChangeSetName: api-deployment
                OutputArtifacts:
                  - Name: !Sub 'prod-ChangeSet-Api-Deployment-Deploy'
                RunOrder: 3
          - !Ref AWS::NoValue