AWSTemplateFormatVersion: 2010-09-09
Description: The 40k Auspex Pipeline

Parameters:
  GitHubRepo:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: auspex
  GitHubBranch:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: master
  Prefix:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"
    Default: ''

Conditions:
  IsProduction: !Equals [!Ref GitHubBranch, "master"]

Resources:
  UiBuildRunner:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ["${Prefix}UiBuildRunner", { Prefix: !Ref Prefix}] 
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value: !ImportValue ArtifactBucketId
          - Name: S3_BUCKET
            Value: !ImportValue ArtifactBucketId
      ServiceRole: !ImportValue BuildExecutionRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/pipeline/buildspecs/ui-build.yaml

  ApiBuildRunner:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ["${Prefix}ApiBuildRunner", { Prefix: !Ref Prefix}]
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value: !ImportValue ArtifactBucketId
          - Name: S3_BUCKET
            Value: !ImportValue ArtifactBucketId
      ServiceRole: !ImportValue BuildExecutionRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/pipeline/buildspecs/api-build.yaml

  DataBuildRunner:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ["${Prefix}DataBuildRunner", { Prefix: !Ref Prefix}] 
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value: !ImportValue ArtifactBucketId
          - Name: S3_BUCKET
            Value: !ImportValue ArtifactBucketId
      ServiceRole: !ImportValue BuildExecutionRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/pipeline/buildspecs/data-build.yaml

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref Prefix
      ArtifactStore:
        Type: S3
        Location: !ImportValue ArtifactBucketId
      RestartExecutionOnUpdate: true
      RoleArn: !ImportValue PipelineInfrastructureRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              InputArtifacts: []
              OutputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: "{{resolve:secretsmanager:Github:SecretString:owner}}"
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                PollForSourceChanges: false
                OAuthToken: "{{resolve:secretsmanager:Github:SecretString:token}}"
              RunOrder: 1
        - Name: Build
          Actions:
          # - Name: Build
          #   ActionTypeId:
          #     Category: Build
          #     Owner: AWS
          #     Version: 1
          #     Provider: CodeBuild
          #   Configuration:
          #     ProjectName: !Ref BuildRunner
          #     BatchEnabled: true
          #   InputArtifacts:
          #     - Name: SourceCode
          #   OutputArtifacts:
          #     - Name: uiBuild_uiBuildOutput
          #   RunOrder: 1
          - Name: BuildUi
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref UiBuildRunner
            InputArtifacts:
              - Name: SourceCode
            OutputArtifacts:
              - Name: uiBuildOutput
              - Name: urlBuildOutput
            RunOrder: 1
          - Name: BuildApi
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref ApiBuildRunner
            InputArtifacts:
              - Name: SourceCode
            OutputArtifacts:
              - Name: apiGatewayBuildOutput
              - Name: apiGatewayDeploymentBuildOutput
            RunOrder: 1
          - Name: BuildData
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref DataBuildRunner
            InputArtifacts:
              - Name: SourceCode
            OutputArtifacts:
              - Name: databaseBuildOutput
              - Name: loadDataBuildOutput
              - Name: dropFilesBuildOutput
            RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployDatabase
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: databaseBuildOutput
              Namespace: db
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: databaseBuildOutput::infrastructure/template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: !Sub ["${Prefix}Database", { Prefix: !Ref Prefix}] 
              RunOrder: 1
            - Name: DeployApi
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: apiGatewayBuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: apiGatewayBuildOutput::infrastructure/template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                StackName: !Sub ["${Prefix}Stack-API", { "Prefix": !Ref Prefix }]
                ParameterOverrides: !Sub |
                  {
                    "TableName": "#{db.DbTableName}",
                    "Prefix": "${Prefix}"
                  }
              RunOrder: 2
            - Name: DeployUiCode
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                BucketName: !ImportValue UiBucketName
                Extract: true
                ObjectKey: !If [IsProduction, 'master', !Ref GitHubBranch]
              InputArtifacts:
                - Name: uiBuildOutput
              Region: us-east-1
              RunOrder: 2
            - Name: DeployApiStage
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: apiGatewayDeploymentBuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: apiGatewayDeploymentBuildOutput::infrastructure/template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                StackName: !Sub ["${Prefix}Stack-Stack-Api-Deployment", { "Prefix": !Ref Prefix }]
                ParameterOverrides: !Sub
                  - '{ "BasePathDomain": "${BasePathDomain}" }'
                  - BasePathDomain: !If [IsProduction, 'api.40kauspex.com', !Sub 'api-${GitHubBranch}.40kauspex.com']
              RunOrder: 3
        - Name: DeployDataLambda
          Actions:
            - Name: DeployLoadDataLambda
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: loadDataBuildOutput
              OutputArtifacts:
                - Name: loadDataDeployOutput
              Namespace: loadData
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: loadDataBuildOutput::template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND,CAPABILITY_NAMED_IAM
                StackName: !Sub ["${Prefix}Load-Data", { Prefix: !Ref Prefix}] 
                OutputFileName: loadDataDeployOutput.json
                ParameterOverrides: !Sub |
                  {
                    "TableName": "#{db.DbTableName}",
                    "Prefix": "${Prefix}"
                  }
              RunOrder: 1
            - Name: DeployDropFilesLambda
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: dropFilesBuildOutput
              Namespace: dropFiles
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: dropFilesBuildOutput::template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND,CAPABILITY_NAMED_IAM
                StackName: !Sub ["${Prefix}Drop-Files", { Prefix: !Ref Prefix}]
                ParameterOverrides: !Sub |
                  {
                    "Prefix": "${Prefix}"
                  }
              RunOrder: 1
        - Name: SeedData
          Actions:
            - Name: DropFiles
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Provider: Lambda
                Version: 1
              Configuration:
                FunctionName: !Sub "#{dropFiles.DropFilesFunctionName}"
                UserParameters: snrauspex-data
              Region: us-east-1
              RunOrder: 1
        # - !If
        #   - IsProduction
        #   - Name: DeploymentApproval
        #     Actions:
        #       - Name: Approval
        #         ActionTypeId:
        #           Category: Approval
        #           Owner: AWS
        #           Provider: Manual
        #           Version: 1
        #         RunOrder: 1
        #   - !Ref AWS::NoValue
        # - !If
        #   - IsProduction
        #   - Name: Production
        #     Actions:
        #       - Name: DeployUiCode
        #         ActionTypeId:
        #           Category: Deploy
        #           Owner: AWS
        #           Provider: S3
        #           Version: 1
        #         RunOrder: 1
        #         Configuration:
        #           BucketName: !ImportValue UiBucketName
        #           Extract: true
        #           ObjectKey: master
        #         InputArtifacts:
        #           - Name: uiBuildOutput
        #         Region: us-east-1
        #       - Name: CreateUIChangeSet
        #         ActionTypeId:
        #           Category: Deploy
        #           Owner: AWS
        #           Provider: CloudFormation
        #           Version: 1
        #         Configuration:
        #           ActionMode: CHANGE_SET_REPLACE
        #           RoleArn: !ImportValue CloudFormationExecutionRoleArn
        #           StackName: 'prod-Stack-UI'
        #           ChangeSetName: ui
        #           TemplatePath: lambdaEdgeBuildOutput::infrastructure/template.package.yaml
        #           Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
        #           ParameterOverrides: '{ "Domain": "40kauspex.com", "BranchName": "master" }'
        #         InputArtifacts:
        #           - Name: lambdaEdgeBuildOutput
        #         RunOrder: 1
        #       - Name: CreateApiChangeSet
        #         ActionTypeId:
        #           Category: Deploy
        #           Owner: AWS
        #           Provider: CloudFormation
        #           Version: 1
        #         InputArtifacts:
        #           - Name: apiGatewayBuildOutput
        #         Configuration:
        #           ActionMode: CHANGE_SET_REPLACE
        #           RoleArn: !ImportValue CloudFormationExecutionRoleArn
        #           StackName: 'prod-Stack-Api'
        #           ChangeSetName: api
        #           TemplatePath: apiGatewayBuildOutput::infrastructure/template.package.yaml
        #           Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
        #           ParameterOverrides: '{ "BasePathDomain": "api.40kauspex.com" }'
        #         RunOrder: 1
        #       - Name: CreateApiDeploymentChangeSet
        #         ActionTypeId:
        #           Category: Deploy
        #           Owner: AWS
        #           Provider: CloudFormation
        #           Version: 1
        #         InputArtifacts:
        #           - Name: apiGatewayDeploymentBuildOutput
        #         Configuration:
        #           ActionMode: CHANGE_SET_REPLACE
        #           RoleArn: !ImportValue CloudFormationExecutionRoleArn
        #           StackName: !Sub 'prod-Stack-Api-Deployment'
        #           ChangeSetName: api-deployment
        #           TemplatePath: apiGatewayDeploymentBuildOutput::infrastructure/template.package.yaml
        #           Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
        #         RunOrder: 1
        #       - Name: ExecuteApiChangeSet
        #         ActionTypeId:
        #           Category: Deploy
        #           Owner: AWS
        #           Provider: CloudFormation
        #           Version: 1
        #         Configuration:
        #           ActionMode: CHANGE_SET_EXECUTE
        #           RoleArn: !ImportValue CloudFormationExecutionRoleArn
        #           StackName: !Sub 'prod-Stack-Api'
        #           ChangeSetName: api
        #         OutputArtifacts:
        #           - Name: !Sub 'prod-ChangeSet-Api-Deploy'
        #         RunOrder: 2
        #       - Name: ExecuteUIChangeSet
        #         ActionTypeId:
        #           Category: Deploy
        #           Owner: AWS
        #           Provider: CloudFormation
        #           Version: 1
        #         Configuration:
        #           ActionMode: CHANGE_SET_EXECUTE
        #           RoleArn: !ImportValue CloudFormationExecutionRoleArn
        #           StackName: !Sub '$prod-Stack-UI'
        #           ChangeSetName: ui
        #         OutputArtifacts:
        #           - Name: !Sub 'prod-ChangeSet-UI-Deploy'
        #         RunOrder: 3
        #       - Name: ExecuteApiDeploymentChangeSet
        #         ActionTypeId:
        #           Category: Deploy
        #           Owner: AWS
        #           Provider: CloudFormation
        #           Version: 1
        #         Configuration:
        #           ActionMode: CHANGE_SET_EXECUTE
        #           RoleArn: !ImportValue CloudFormationExecutionRoleArn
        #           StackName: !Sub 'prod-Stack-Api-Deployment'
        #           ChangeSetName: api-deployment
        #         OutputArtifacts:
        #           - Name: !Sub 'prod-ChangeSet-Api-Deployment-Deploy'
        #         RunOrder: 3
        #   - !Ref AWS::NoValue