AWSTemplateFormatVersion: 2010-09-09
Description: The Monster of the Week Pipeline

Parameters:
  GitHubRepo:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: monster-of-week
  GitHubBranch:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: master

Resources:
  BuildRunner:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-BuildRunner
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value: !ImportValue ArtifactBucketId
      ServiceRole: !ImportValue BuildExecutionRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/pipeline/buildspec-build.yaml

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${AWS::StackName}
      ArtifactStore:
        Type: S3
        Location: !ImportValue ArtifactBucketId
      RestartExecutionOnUpdate: true
      RoleArn: !ImportValue PipelineInfrastructureRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              InputArtifacts: []
              OutputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: "{{resolve:secretsmanager:Github:SecretString:owner}}"
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                PollForSourceChanges: false
                OAuthToken: "{{resolve:secretsmanager:Github:SecretString:token}}"
              RunOrder: 1
        - Name: Build
          Actions:
          # - Name: BuildDns
          #   ActionTypeId:
          #     Category: Deploy
          #     Owner: AWS
          #     Provider: CloudFormation
          #     Version: 1
          #   InputArtifacts:
          #     - Name: SourceCode
          #   Configuration:
          #     ActionMode: CREATE_UPDATE
          #     StackName: !Sub '${AWS::StackName}-dns'
          #     TemplatePath: SourceCode::infrastructure/url/template.yaml
          #     RoleArn: !ImportValue PipelineInfrastructureRoleArn
          #     Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
          #   RunOrder: 1
          - Name: BuildAndTest
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref BuildRunner
            InputArtifacts:
              - Name: SourceCode
            OutputArtifacts:
              - Name: BuildOutput
            RunOrder: 1
        - Name: Staging
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !ImportValue PipelineInfrastructureRoleArn
                StackName: !Sub '${AWS::StackName}-Stack-Beta'
                ChangeSetName: !Sub '${AWS::StackName}-ChangeSet-Beta'
                TemplatePath: BuildOutput::ui.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: '{ "Stage": "staging" }'
              InputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn: !ImportValue PipelineInfrastructureRoleArn
                StackName: !Sub '${AWS::StackName}-Stack-Beta'
                ChangeSetName: !Sub '${AWS::StackName}-ChangeSet-Beta'
              OutputArtifacts:
                - Name: !Sub '${AWS::StackName}-ChangeSet-Beta'
              RunOrder: 2
        - Name: Production
          Actions:
            - Name: DeploymentApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              RunOrder: 1
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !ImportValue PipelineInfrastructureRoleArn
                StackName: !Sub '${AWS::StackName}-Stack-Prod'
                ChangeSetName: !Sub '${AWS::StackName}-ChangeSet-Prod'
                TemplatePath: BuildOutput::ui.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: '{ "Stage": "production" }'
              InputArtifacts:
                - Name: BuildOutput
              RunOrder: 2
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn: !ImportValue PipelineInfrastructureRoleArn
                StackName: !Sub '${AWS::StackName}-Stack-Prod'
                ChangeSetName: !Sub '${AWS::StackName}-ChangeSet-Prod'
              OutputArtifacts:
                - Name: !Sub '${AWS::StackName}-ChangeSet-Prod'
              RunOrder: 3
          
        # - Name: Deploy
        #   Actions:
        #   - Name: DeployUiCode
        #     ActionTypeId:
        #       Category: Deploy
        #       Owner: AWS
        #       Provider: S3
        #       Version: 1
        #     RunOrder: 1
        #     Configuration:
        #       BucketName: !ImportValue UiBucketName
        #       Extract: true
        #     InputArtifacts:
        #       - Name: BuildOutput
        #     Region: us-east-1
