AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Monster of the Week api gateway deployment

Parameters:
  BasePathDomain:
    Type: String
    Default: ''
  HostedZoneId:
    Type: String
    Default: Z0953270AK2JGXA33JIB
  StageName:
    Type: String
    AllowedValues:
      - prod
      - v1
    ConstraintDescription: Please enter a valid environment ('prod' or starting with 'v')

Resources:
  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !ImportValue ApiGatewayId
      StageName: !Ref StageName

  ApiGatewayDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref BasePathDomain
      RegionalCertificateArn: arn:aws:acm:us-east-1:625961017727:certificate/edd15537-9b78-4e21-a100-9ce277ca42bf
      EndpointConfiguration:
        Types:
          - REGIONAL

  V1ApiGatewayDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      Stage: v1
      BasePath: v1
      DomainName: !Ref ApiGatewayDomainName
      RestApiId: !ImportValue ApiGatewayId
    DependsOn: ApiGatewayDomainName

  V2ApiGatewayDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      Stage: v2
      BasePath: v2
      DomainName: !Ref ApiGatewayDomainName
      RestApiId: !ImportValue ApiGatewayId
    DependsOn: ApiGatewayDomainName

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt ApiGatewayDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt ApiGatewayDomainName.RegionalHostedZoneId
      HostedZoneId: !Ref HostedZoneId
      Name: !Join [ "", [ !Ref BasePathDomain, "." ] ]
      Type: A