AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Monster of the Week api gateway deployment

Parameters:
  StageName:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
  BasePathDomain:
    Type: String
    Default: ''
  HostedZoneId:
    Type: String
    Default: Z0953270AK2JGXA33JIB

Conditions:
  IsBlue: !Equals [!Ref StageName, "blue"]

Resources:
  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !ImportValue ApiGatewayId
      StageName: !Ref StageName
      # DeploymentCanarySettings:
      #   PercentTraffic: 0

  ApiGatewayDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref BasePathDomain
      RegionalCertificateArn: arn:aws:acm:us-east-1:625961017727:certificate/edd15537-9b78-4e21-a100-9ce277ca42bf
      EndpointConfiguration:
        Types:
          - REGIONAL

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt ApiGatewayDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt ApiGatewayDomainName.RegionalHostedZoneId
      HostedZoneId: !Ref HostedZoneId
      Name: !Join [ "", [ !Ref BasePathDomain, "." ] ]
      Type: A

  # BlueStage:
  #   Type: AWS::ApiGateway::Stage
  #   Properties:
  #     RestApiId: !ImportValue ApiGatewayId
  #     StageName: blue
  #     DeploymentId: !Ref Deployment
  #     MethodSettings:
  #       - HttpMethod: '*'
  #         ResourcePath: /*
  #         ThrottlingRateLimit: 1000
  #         ThrottlingBurstLimit: 500

  # GreenStage:
  #   Type: AWS::ApiGateway::Stage
  #   Properties:
  #     RestApiId: !ImportValue ApiGatewayId
  #     StageName: green
  #     DeploymentId: !Ref Deployment
  #     MethodSettings:
  #       - HttpMethod: '*'
  #         ResourcePath: /*
  #         ThrottlingRateLimit: 1000
  #         ThrottlingBurstLimit: 500

  # BlueUrl:
  #   Type: AWS::ApiGateway::BasePathMapping
  #   Properties:
  #     DomainName: !Ref BasePathDomain
  #     RestApiId: !ImportValue ApiGatewayId
  #     Stage: !Ref BlueStage
  #     BasePath: blue

  # GreenUrl:
  #   Type: AWS::ApiGateway::BasePathMapping
  #   Properties:
  #     DomainName: !Ref BasePathDomain
  #     RestApiId: !ImportValue ApiGatewayId
  #     Stage: !Ref GreenStage
  #     BasePath: green

  SSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /api-gateway/next-stage
      Description: The stage of the api gateway for the next deploy
      Type: String
      Value: !If [IsBlue, "green", "blue"]