AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Monster of the Week api gateway deployment

Parameters:
  BasePathDomain:
    Type: String
    Default: ''
  HostedZoneId:
    Type: String
    Default: Z0953270AK2JGXA33JIB

Resources:
  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !ImportValue ApiGatewayId
      StageName: prod

  ApiGatewayDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref BasePathDomain
      RegionalCertificateArn: arn:aws:acm:us-east-1:625961017727:certificate/edd15537-9b78-4e21-a100-9ce277ca42bf
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiGatewayDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: prod
      DomainName: !Ref ApiGatewayDomainName
      RestApiId: !ImportValue ApiGatewayId
    DependsOn: ApiGatewayDomainName

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt ApiGatewayDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt ApiGatewayDomainName.RegionalHostedZoneId
      HostedZoneId: !Ref HostedZoneId
      Name: !Join [ "", [ !Ref BasePathDomain, "." ] ]
      Type: A