AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Monster of the Week api gateway deployment

Parameters:
  StageName:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: prod
  BasePathDomain:
    Type: String
    Default: ''
  HostedZoneId:
    Type: String
    Default: Z0953270AK2JGXA33JIB

Resources:
  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !ImportValue ApiGatewayId
      # StageName: blue
      # DeploymentCanarySettings:
      #   PercentTraffic: 0

  #  BlueGreenDeployment:
  #   Type: AWS::ApiGatewayV2::Deployment
  #   Properties:
  #     ApiId: !ImportValue ApiGatewayId
  #     Description: Blue/Green deployment for API Gateway
  #     DeploymentCanarySettings:
  #       PercentTraffic: 0
  #       StageVariableOverrides:
  #         BLUE_GREEN: "green"
  #       UseStageCache: true

  # BlueGreenAlias:
  #   Type: AWS::ApiGatewayV2::ApiMapping
  #   Properties:
  #     ApiId: !ImportValue ApiGatewayId
  #     Stage: prod
  #     DomainName: !GetAtt ApiGatewayDomainName.RegionalDomainName
  #     ApiMappingKey: blue-green

  # MyBlueGreenRoute:
  #   Type: AWS::ApiGatewayV2::Route
  #   Properties:
  #     ApiId: !ImportValue ApiGatewayId
  #     RouteKey: $default
  #     Target: !Join
  #       - "/"
  #       - - 'integrations'
  #         - !Ref MyIntegration
  #     RouteResponseSelectionExpression: "$default"

  # Stage:
  #   Type: AWS::ApiGateway::Stage
  #   Properties:
  #     StageName: !Ref StageName
  #     RestApiId: !ImportValue ApiGatewayId
  #     DeploymentId: !Ref Deployment

  # BasePathMapping:
  #   Type: AWS::ApiGateway::BasePathMapping
  #   Properties:
  #     DomainName: !Ref ApiGatewayDomainName
  #     RestApiId: !ImportValue ApiGatewayId
  #     Stage: !Ref Stage

  ApiGatewayDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref BasePathDomain
      RegionalCertificateArn: arn:aws:acm:us-east-1:625961017727:certificate/edd15537-9b78-4e21-a100-9ce277ca42bf
      EndpointConfiguration:
        Types:
          - REGIONAL

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt ApiGatewayDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt ApiGatewayDomainName.RegionalHostedZoneId
      HostedZoneId: !Ref HostedZoneId
      Name: !Join [ "", [ !Ref BasePathDomain, "." ] ]
      Type: A

  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !ImportValue ApiGatewayId
      StageName: !Ref StageName
      DeploymentId: !Ref Deployment
      MethodSettings:
        - HttpMethod: '*'
          ResourcePath: /*
          ThrottlingRateLimit: 1000
          ThrottlingBurstLimit: 500

  # GreenStage:
  #   Type: AWS::ApiGateway::Stage
  #   Properties:
  #     RestApiId: !ImportValue ApiGatewayId
  #     StageName: green
  #     DeploymentId: !Ref Deployment
  #     MethodSettings:
  #       - HttpMethod: '*'
  #         ResourcePath: /*
  #         ThrottlingRateLimit: 2000
  #         ThrottlingBurstLimit: 1000

  Url:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref BasePathDomain
      RestApiId: !ImportValue ApiGatewayId
      Stage: !Ref Stage
      BasePath: !Ref StageName

  # GreenUrl:
  #   Type: AWS::ApiGateway::BasePathMapping
  #   Properties:
  #     DomainName: !Ref BasePathDomain
  #     RestApiId: !ImportValue ApiGatewayId
  #     Stage: !Ref GreenStage
  #     BasePath: green