AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Monster of the Week api gateway deployment

Resources:
  ApiGatwayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !ImportValue ApiGatewayId