name: Create pipeline
on:
  workflow_dispatch: {}
  pull_request: {}
jobs:
  CreatePipelineLamda:
   runs-on: ubuntu-latest
   steps:
    - name: Set branch name
      id: branch
      run:  echo "::set-output name=${{ github.head_ref || github.ref_name }}"
    - name: Checkout branch
      uses: actions/checkout@master
    - name: Upload pipeline template to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      id: templateUpload
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        SOURCE_DIR: 'infrastructure/ciCd/createPipelineLambda/infrastructure'
        AWS_REGION: 'us-east-1'
        DEST_DIR: ${{ steps.branch.outputs.name }}
    - name: Invoke create pipeline lambda
      uses: gagoar/invoke-aws-lambda@master
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FunctionName: CreatePipeline
        Payload: '{ "BranchName": "${{ steps.branch.outputs.name }}", "TemplateUrl": "s3://cf-templates-j0zgzjgqfdcl-us-east-1/${{ steps.branch.outputs.name }}/template.yaml" }'