name: Create pipeline
on:
  workflow_dispatch: {}
  pull_request: {}
jobs:
  CreatePipelineLamda:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout branch
      uses: actions/checkout@master
    - name: Upload pipeline template to S3 bucket
      uses: shallwefootball/s3-upload-action@master
      id: templateUpload
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: 'infrastructure/ciCd/createPipelineLambda/infrastructure'
        destination_dir: ''
    - name: Invoke create pipeline lambda
      uses: gagoar/invoke-aws-lambda@master
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FunctionName: CreatePipeline
        Payload: '{ "BranchName": "${{ github.head_ref || github.ref_name }}", "TemplateUrl": "${{ steps.templateUpload.outputs.object_locations }}" }'