name: Create pipeline
on:
  workflow_dispatch: {}
  pull_request: {}
jobs:
  CreatePipelineLamda:
   runs-on: ubuntu-latest
   steps:
    - name: Check workspace
      run: echo "${{ GITHUB_SERVER_URL }}/${{ GITHUB_REPOSITORY }}"
    - name: Invoke create pipeline lambda
      uses: gagoar/invoke-aws-lambda@master
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FunctionName: CreatePipeline
        Payload: '{ "BranchName": "${{ github.head_ref || github.ref_name }}" }'