name: Delete pipeline
on:
  workflow_dispatch: {}
  delete: {}
jobs:
  DeletePipelineLamda:
   runs-on: ubuntu-latest
   steps:
    - name: Invoke create pipeline lambda
      uses: gagoar/invoke-aws-lambda@master
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FunctionName: DeletePipeline
        Payload: '{ "BranchName": "${{ github.head_ref || github.ref_name }}" }'