name: Create a Pipeline
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
   runs-on: ubuntu-latest
   permissions:
    contents: read
    packages: write
  steps:
   - name: Check repository
     uses: actions/checkout@v2
   - name: Configure AWS Credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1
   - name: Deploy to AWS CloudFormation
     uses: aws-actions/aws-cloudformation-github-deploy@v1
     with:
      name: pipeline-stack-${GITHUB_REF##*/}
      template: infrastructure/pipeline/template.yaml
      parameter-overrides: "GitHubBranch=${GITHUB_REF##*/}"